### DISCUSSION TITLE
Can someone please help me.

### DISCUSSION THREAD

**Discussion by jerry-lockard** [bluesky-social/atproto#2667] [Clarifications and "Why?"]
I have been trying to follow along with the docs for atproto & I'm so confused on how to get it up & running, I even started asking ChatGPT for help, I went through this discussion board to see if there was anyone else having this issue. I'm attaching a screenshot of the issue, when I got into atproto & run pnpm install or even make deps, but I keep getting errors. Also I'm relatively new at this, so please forgive me. I been teaching myself coding the past year.
<img width="811" alt="github" src="https://github.com/user-attachments/assets/ca1d6312-c31c-4577-9fa6-445e415c6760">
<img width="814" alt="image" src="https://github.com/user-attachments/assets/ab4703be-4b0d-4a99-86b5-d08129103a4f">

**Comment by DavidBuchanan314** [comment]
What is your goal?

**Reply by jerry-lockard** [reply]
I just want to get it up and running to build this https://github.com/bluesky-social/social-app.git for android. After bluesky social-ap initial setup it says to clone the atproto and start the server. That's as far as I get, then I get those errors. I have pds already running with my domain but I don't understand what to do.

**Reply by syui** [reply]
To run the social app, we recommend using a Dockerfile. If you prefer to build it locally, please refer to the environment settings used in the Dockerfile.

## example

```sh
$ vim compose.yml
```

```yml
services:

  social-app:
    ports:
      - 8100:8100
    image: itaru2622/bluesky-social-app
    restart: always
    command: "/usr/bin/bskyweb serve"
    environment:
      - ATP_APPVIEW_HOST=https://bsky.social
      - NODE_ENV=development
      - GOLOG_LOG_LEVEL=info
```

- https://github.com/itaru2622/bluesky-selfhost-env/blob/master/docker-compose.yaml

```sh
# install and start docker
$ sudo pacman -S docker docker-compose
$ sudo systemctl start docker

$ sudo docker compose build
$ sudo docker compose up
```

or 

```sh
$ mkdir tmp
$ cd tmp
$ git clone https://github.com/bluesky-social/social-app.git
$ vim compose.yml
```

> compose.yml

```yml
services:

  social-app:
    ports:
      - 8100:8100
    build:
      context: ./social-app/
      dockerfile: Dockerfile
    restart: always
    command: "/usr/bin/bskyweb serve"
    environment:
      - ATP_APPVIEW_HOST=https://bsky.social
      - NODE_ENV=development
      - GOLOG_LOG_LEVEL=info
```
