### DISCUSSION TITLE
Support for "Badges" for positive labels as a first-class citizen

### DISCUSSION THREAD

**Discussion by Hoid** [bluesky-social/atproto#3065] [Protocol (atproto)]
Currently, labels are understood to be used in both the "negative" sense that you are labeling content to be filtered somehow by users' labeler preferences/identifying content as negative in some way, and in the "positive" sense in which you are giving your profile some sort of label that shows some trait you have. I want to argue that these "positive" applications of labels don't make sense as labels, which is evidenced by the current lack of good support for them in Ozone, and that they should instead be called "badges". This would need to be a new functionality added to the protocol, rather than split away from labelers, because I think badges themselves should be able to be labeled ("Intolerant" if the badge is intolerant of a protected class, "Nudity" if the icon has nudity, etc.).

"Badges" would be what we call that which we now understand as "positive labels". They could be shown under the user's handle as icons, one for each badge, and the user can even see what badges they have within the app so they can decide on order/which ones you have to click on the handle to see. These positive labels such as "Game Dev", "Kiki/Bouba", or what time zone you live in make more sense as badges because currently they look the same as negative labels and people get confused when subscribing to a positive labeler that they must be assigning those labels to themselves, rather than showing a certain badge or not. A user must be subscribed to the "badge collector" (or whatever you want to call it) for that badge collector to assign them a badge, which is more strict than labelers, but that's because I think users should be able to see what badges they've been given and choose which ones to display on their profile, and in which order. These badges would be visible to everyone on your profile/under your handle, regardless of whether they've subscribed to the badge collector. The fact that these badges can themselves be labeled will prevent certain types of badges from being seen by people that don't want to see that kind of content ("Adult Content", "Self-Harm", etc.). 

Labels make more sense as ways for users to both filter how they want to see certain content and to inform users on moderation decisions (so users can see an account is labeled as Intolerant, for example). Badges make more sense as ways for users to display parts of their identity, and to be able to control how those badges are shown. So I'd like to see them diverged, rather than everything being "labels".

Edit: word choice

**Comment by yamarten** [comment]
Is [Blue Badge](https://badge.blue/) almost what you want? However, the client and settings that display it in the Bluesky profile are missing.

**Reply by alekcunn** [reply]
wow. nice

**Reply by Hoid** [reply]
I think Blue Badge theoretically could support what I'm talking about, and it would be really cool for Bluesky PBC to start building a dependency on another open-source project into their main app flow. But I'm not completely sure how it works. I found the most up-to-date record for the example on the front page of https://badge.blue in [ngerakines.me](https://atproto-browser.vercel.app/at/ngerakines.me)'s repo under the following URL: https://atproto-browser.vercel.app/at/did:plc:cbkjy5n7bk3ax2wplmtjofq2/blue.badge.collection/3l2npthykb226. That record is as follows:

```
uri: "at://did:plc:cbkjy5n7bk3ax2wplmtjofq2/blue.badge.collection/3l2npthykb226"
cid: "bafyreiaqx3k3asw2zg7fnvxz2bm4i7ju6xwq7svqkvkgskcclpeuqdzjny"
value:
    did: "did:plc:cbkjy5n7bk3ax2wplmtjofq2"
    $type: "blue.badge.award"
    badge:
        cid: "bafyreifbq7wub6wfuntruagvaaivqsinxyc4mpbfagjka35v4wx7aeu3fe"
        uri: "at://did:plc:puy52u7opoy3gvrv7h7qdy76/blue.badge.definition/6XXzn32gbU"
        name: "Adventure Awaits!"
        description: "You're in for an adventure! Log in for the first time to https://atproto.camp/."
    proof:
        k: "https://atproto.camp/.well-known/jwks.json#01J67HHM2CCKT98FE20SKPR5EA"
        s: "2-EaPZELcvu5SL8lS863fta8moqLZcpKlrzFpn7RbUr_B37HZphJa642dJfGNM2BMZGl-YGQync-2pyhoPC4Wg=="
    issued: "2024-08-26T22:14:02.000Z"
```

But the `badge` field of the record above doesn't match the following `blue.badge.definition` record exactly, pulled straight from the URI in the `uri` field above, which is confusing:

```
uri: "at://did:plc:puy52u7opoy3gvrv7h7qdy76/blue.badge.definition/6XXzn32gbU"
cid: "bafyreidcl5bkqjc456py6iukcod6kl2djqea5bdcwraga2xuiag64j4eym"
value:
    name: "Adventure Awaits!"
    text: "You're in for an adventure! Log in for the first time to https://atproto.camp/."
    $type: "blue.badge.definition"
    image: "https://atproto.camp/static/6XXzn32gbU.png"
```

This record contains a `uri` and `cid`, like the `badge` field in the `blue.badge.collection` record above it, but instead of `name` and `description` there's `value.name`, `value.text`, `value.$type`, and `value.image`. I'm just not sure how that all plays together. I'm glad to see it supports images for each badge definition though! Those would be necessary for frontend clients to display next to/underneath handles, at least in my original proposal. 

@ngerakines, any thoughts on why badge.blue is this way above?
