### ISSUE TITLE
Hugo (https://gohugo.io) site plugin?

### ISSUE THREAD

**Issue by ewanc26** [bluesky-social/atproto#2526]
**Is your feature request related to a problem? Please describe.**

I'd like to automatically have [my website](https://ewancroft.uk) (built with the Hugo site builder) post to [my Bluesky / ATProto account](https://bsky.app/profile/ewancroft.uk) when there is a new blog post.

**Describe the solution you'd like**

I was thinking there could be a drop-in [shortcode](https://gohugo.io/content-management/shortcodes/) or something that could be dynamically configured to target certain sections (such as [my blog section](https://ewancroft.uk/blog)) of a Hugo site. 

**Describe alternatives you've considered**

I know there are already some implementations for sites, but I do not want to rebuild my site on something else than Hugo.

**Additional context**

I imagine that the posts could look similar to this, pulling the information from the front matter:

```yaml
---
title: "Logistics of Lycanthropy and its Romanticisation"
summary: "An analysis of the logistical nature of the lycanthropic curse, and how it's changed over time."
date: 2024-01-24T04:26:42Z
draft: false
tags: ['Werewolves', 'History']
ShowToc: true
---
```

![image](https://github.com/bluesky-social/atproto/assets/156911937/63521f9e-bf3d-4215-a2b6-314440a7564f)
